package com.randomwaterreminder.app

data class ReminderConfig(
    val enabled: Boolean = false,
    val startHour: Int = 6,
    val startMinute: Int = 35,
    val endHour: Int = 23,
    val endMinute: Int = 45,
    val minIntervalMinutes: Int = 35,
    val maxIntervalMinutes: Int = 45,
    val nextReminderTime: Long = 0L,
    val waterNotificationTitle: String = "该喝水啦",
    val waterNotificationText: String = "稳健做人，认真做事。",
    val waterSoundMode: String = "default",
    val waterCustomSoundUri: String = "",
    val waterCustomSoundName: String = "",
    val waterVolumePercent: Int = 100,
    val screenLimitEnabled: Boolean = true,
    val screenOnLimitMinutes: Int = 5,
    val requiredScreenOffMinutes: Int = 5,
    val cancelBeforeLockCount: Int = 5,
    val screenSoundMode: String = "default",
    val screenCustomSoundUri: String = "",
    val screenCustomSoundName: String = "",
    val screenVolumePercent: Int = 100,
)
